baseURL = 'http://localhost:1313/'
languageCode = 'es-mx'
title = 'Dosis de Ciencia'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  author = "Carlos"
  description = "Divulgación científica clara y poderosa"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Artículos"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Sobre mí"
    url = "/sobre-mi/"
    weight = 3
